connector_image: airbyte/source-yandex-metrica:dev
acceptance_tests:
  spec:
    tests:
      - spec_path: source_yandex_metrica/spec.yaml
  connection:
    tests:
      - config_path: secrets/config.json
        status: succeed
      - config_path: integration_tests/invalid_config.json
        status: failed
  discovery:
    tests:
      - config_path: secrets/config.json
  basic_read:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
        expect_records:
          path: integration_tests/expected_records.jsonl
          exact_order: false
        timeout_seconds: 3600
  full_refresh:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
        timeout_seconds: 3600
  incremental:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
        timeout_seconds: 3600
        future_state:
          future_state_path: integration_tests/abnormal_state.json
