connector_image: airbyte/source-fauna:dev
acceptance_tests:
  spec:
    tests:
      - spec_path: source_fauna/spec.yaml
  connection:
    tests:
      - config_path: secrets/config.json
        status: succeed
      - config_path: secrets/config-deletions.json
        status: succeed
      - config_path: integration_tests/config/invalid.json
        status: failed
  discovery:
    tests:
      - config_path: secrets/config.json
      - config_path: secrets/config-deletions.json
  basic_read:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
        empty_streams: []
        expect_records:
          path: integration_tests/expected_records.jsonl
          exact_order: true
      - config_path: secrets/config-deletions.json
        configured_catalog_path: integration_tests/configured_catalog_incremental.json
        empty_streams: []
        expect_records:
          path: integration_tests/expected_deletions_records.txt
          exact_order: true
  incremental:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
        future_state:
          # Note that the time in this file was generated with this fql:
          # ToMicros(ToTime(Date("9999-01-01")))
          future_state_path: integration_tests/abnormal_state.json
      - config_path: secrets/config-deletions.json
        configured_catalog_path: integration_tests/configured_catalog_incremental.json
        future_state:
          future_state_path: integration_tests/abnormal_deletions_state.json
  full_refresh:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
