connector_image: airbyte/source-firebase-realtime-database:dev
acceptance_tests:
  spec:
    tests:
      - spec_path: source_firebase_realtime_database/spec.yaml
  connection:
    tests:
      - config_path: secrets/config.json
        status: succeed
      - config_path: integration_tests/invalid_config.json
        status: failed
  discovery:
    tests:
      - config_path: secrets/config.json
  basic_read:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
        empty_streams: []
        expect_records:
          path: integration_tests/expected_records.txt
          exact_order: false
  full_refresh:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
