connector_image: airbyte/source-mssql:dev
acceptance_tests:
  spec:
    tests:
      - spec_path: src/test-integration/resources/expected_spec.json
        config_path: src/test-integration/resources/dummy_config.json
        backward_compatibility_tests_config:
          disable_for_version: 0.4.25
