connector_image: airbyte/source-callrail:dev
acceptance_tests:
  spec:
    tests:
      - spec_path: manifest.yaml
        timeout_seconds: 60
  connection:
    tests:
      - config_path: secrets/config.json
        status: succeed
      - config_path: integration_tests/invalid_config.json
        status: failed
  discovery:
    tests:
      - config_path: secrets/config.json
  basic_read:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
        empty_streams:
          - name: calls
          - name: conversations
  full_refresh:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
