connector_image: airbyte/source-secoda:dev
acceptance_tests:
  spec:
    tests:
      - spec_path: manifest.yaml
  connection:
    tests:
      - config_path: secrets/config.json
        status: succeed
      - config_path: integration_tests/invalid_config.json
        status: failed
