connector_image: airbyte/source-dockerhub:dev
acceptance_tests:
  spec:
    tests:
      - spec_path: manifest.yaml
        backward_compatibility_tests_config:
          disable_for_version: 0.1.0
  connection:
    tests:
      - config_path: secrets/config.json
        status: succeed
      # even with an incorrect username the api still returns 200 so just ignoring the invalid config check for now
      # - config_path: "integration_tests/invalid_config.json"
      #   status: "failed"
  discovery:
    tests:
      - config_path: secrets/config.json
        backward_compatibility_tests_config:
          disable_for_version: 0.1.0
  basic_read:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
        empty_streams: []
  full_refresh:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
        # testing sequentially for same results can fail because of pull counts increasing for an image between runs
        ignored_fields:
          docker_hub:
            - name: pull_count
            - name: last_updated
