connector_image: airbyte/source-orb:dev
acceptance_tests:
  spec:
    tests:
      - spec_path: manifest.yaml
        backward_compatibility_tests_config:
          disable_for_version: 0.1.4
  connection:
    tests:
      - config_path: secrets/config.json
        status: succeed
      - config_path: integration_tests/invalid_config.json
        status: failed
  discovery:
    tests:
      - config_path: secrets/config.json
  basic_read:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
        fail_on_extra_columns: false
        empty_streams:
          - name: credits_ledger_entries
      - config_path: secrets/config_credits_ledger_entries.json
        configured_catalog_path: integration_tests/configured_catalog_credits.json
  incremental:
    tests:
      - config_path: secrets/config_credits_ledger_entries.json
        configured_catalog_path: integration_tests/configured_catalog_credits.json
        future_state:
          future_state_path: integration_tests/abnormal_state_credits.json
  full_refresh:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
