connector_image: airbyte/source-gridly:dev
acceptance_tests:
  spec:
    tests:
      - spec_path: source_gridly/spec.yaml
        backward_compatibility_tests_config:
          disable_for_version: 0.1.0
  connection:
    tests:
      - config_path: secrets/config.json
        status: succeed
      - config_path: integration_tests/invalid_config.json
        status: failed
  discovery:
    tests:
      - config_path: secrets/config.json
  basic_read:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
        empty_streams: []
  full_refresh:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
