connector_image: airbyte/source-rki-covid:dev
acceptance_tests:
  spec:
    tests:
      - spec_path: source_rki_covid/spec.json
  connection:
    tests:
      - config_path: secrets/config.json
        status: succeed
  discovery:
    tests:
      - config_path: secrets/config.json
  basic_read:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
        empty_streams:
          - name: germany
          - name: germany_age_groups
          - name: german_history_frozen_incidence
          - name: germany_states_age_groups
  incremental:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog_incremental.json
        future_state:
          future_state_path: integration_tests/abnormal_state.json
  full_refresh:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
