connector_image: airbyte/source-sftp:dev
acceptance_tests:
  spec:
    tests:
      - spec_path: src/test-integration/resources/expected_spec.json
        config_path: src/test-integration/resources/dummy_config.json
