connector_image: airbyte/source-looker:dev
acceptance_tests:
  spec:
    tests:
      - spec_path: source_looker/spec.yaml
  connection:
    tests:
      - config_path: secrets/config.json
        status: succeed
      - config_path: integration_tests/invalid_config.json
        status: failed
  discovery:
    tests:
      - config_path: secrets/config.json
  basic_read:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
        empty_streams:
          - name: scheduled_plans
          - name: user_attribute_group_values
          - name: user_login_lockouts
          - name: user_sessions
  full_refresh:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
        ignored_fields:
          datagroups:
            - name: properties
            - name: trigger_check_at
          looks:
            - name: properties
            - name: last_accessed_at
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_run_looks_catalog.json
  incremental:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
        future_state:
          future_state_path: integration_tests/abnormal_state.json
