connector_image: airbyte/source-google-directory:dev
acceptance_tests:
  spec:
    tests:
      - spec_path: source_google_directory/spec.json
  connection:
    tests:
      - config_path: secrets/config.json
        status: succeed
      - config_path: integration_tests/invalid_config.json
        status: failed
  discovery:
    tests:
      - config_path: secrets/config.json
  basic_read:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
  full_refresh:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
        # API returns different lastLoginTime for some users, eteg is generated based on all data, so also sometime are different
        ignored_fields:
          users:
            - name: etag
            - name: lastLoginTime
