[build-system]
requires = ["setuptools>=58.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "${JAVA_RUNTIME_PROJECT_NAME}-${PLATFORM}"
authors = [{name = "Airbyte", email = "contact@airbyte.io"}]
description = "${PLATFORM} java runtime for ${CONNECTOR_TYPE} ${CONNECTOR_NAME}"
version = "0.0.1" #TODO: use "${CONNECTOR_VERSION}" when we start using real versioning

[tool.setuptools.packages.find]
where = ["."]
include = ["${JAVA_RUNTIME_PACKAGE_NAME}"]

[tool.setuptools]
include-package-data = true
