name: Auto merge connector PRs Cron

on:
  schedule:
    # Every 2 hours on the hour.
    - cron: "0 */2 * * *"
  workflow_dispatch:
jobs:
  run_auto_merge:
    name: Run auto-merge
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get tool versions
        uses: marocchino/tool-versions-action@v1
        id: tool-versions
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ steps.tool-versions.outputs.python }}
          check-latest: true
          update-environment: true
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          # Todo: Update to latest (2.x) Poetry version
          version: ${{ steps.tool-versions.outputs.poetry-1 }}
      - name: Run auto merge
        shell: bash
        working-directory: airbyte-ci/connectors/auto_merge
        env:
          # We need a custom Github Token as some API endpoints
          # are not available from GHA auto generated tokens
          # like the one to list branch protection rules...
          GITHUB_TOKEN: ${{ secrets.GH_PAT_MAINTENANCE_OSS }}
          AUTO_MERGE_PRODUCTION: ${{ vars.ENABLE_CONNECTOR_AUTO_MERGE }}
        run: |
          poetry install
          poetry run auto-merge
