# .github/workflows/pr-orchestrator.yml
name: Community Connector CI for Fork PRs

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  contents: read            # to inspect repo metadata
  issues: write             # to post comments
  checks: write             # to create a check run

jobs:
  dispatch-connector-tests:
    # Only run for PRs from forks
    if: ${{ github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name }}
    runs-on: ubuntu-latest
    steps:

      # 1. Try to mint an App token; if it fails, the App isn't installed
      - name: Create GitHub App installation token
        id: create-token
        uses: actions/create-github-app-token@v2
        with:
          app-id:          ${{ secrets.APP_ID }}
          private-key:     ${{ secrets.PRIVATE_KEY }}
          organization:    ${{ github.event.pull_request.head.repo.name }}
          repositories:    airbyte
        continue-on-error: true

      # 2a. If token minting failed, notify contributor.
      #     (Subsequent steps will be skipped.)
      - name: Ask contributor to install the App
        if: ${{ steps.create-token.outcome == 'failure' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          skip_unchanged: true
          header: fork-app-install-status-comment
          message: |
            🚧 To run Connector CI on your fork, please install the Connector CI GitHub App in your forked repo and retry.

      # 2b. If token minting succeeded, thank the contributor.
      - name: Thank contributor for installing the App
        if: ${{ steps.create-token.outcome == 'success' }}
        uses: peter-evans/create-or-update-comment@v3
        with:
          token:           ${{ secrets.GITHUB_TOKEN }}
          issue-number:    ${{ github.event.pull_request.number }}
          body: |
            💙 _Thank you!_ 🙏 You have successfully installed the Airbyte GitHub App in your fork.
            Tests will now be run in the context of your repo, leveraging your own BYO Connector Credentials.

      # 3. Dispatch Connector Tests in fork
      - name: Dispatch Connector Tests in fork
        if: ${{ steps.create-token.outcome == 'success' }}
        uses: peter-evans/workflow-dispatch@v1
        with:
          token:       ${{ steps.create-token.outputs.token }}
          repository:  ${{ github.event.pull_request.head.repo.full_name }}
          workflow:    path/to/connector-tests.yml
          ref:         ${{ github.event.pull_request.head.ref }}
          inputs: |
            connector_names: '["source-mysql","source-postgres"]'

      # 4. Post a final status in a check run in the main repo
      - name: Create Summary Check Run
        if: always() && steps.create-token.outcome == 'success'
        uses: peter-evans/create-check@v3
        with:
          name:       Connector CI Checks Summary
          token:      ${{ secrets.GITHUB_TOKEN }}
          head-sha:   ${{ github.event.pull_request.head.sha }}
          status:     completed
          conclusion: ${{ job.status }}
