name: Documentation Markdown Lint

# This workflow runs MarkDownLint on changed docs files in pull requests. More info: https://docs.airbyte.com/platform/next/contributing-to-airbyte/writing-docs#lint-with-markdownlint

on:
  pull_request:
    # Only trigger if Markdown files in /docs/ change
    paths:
      - "docs/**/*.md"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # Detect changed Markdown files in the PR
      - uses: tj-actions/changed-files@v46
        id: changed-files
        with:
          files: "docs/**/*.md"
          separator: ","

      # Run MarkdownLint on changed files
      - uses: DavidAnson/markdownlint-cli2-action@v20
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          globs: ${{ steps.changed-files.outputs.all_changed_files }}
          separator: ","
          config: .markdownlint.jsonc
        continue-on-error: true
